version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: ghcr.io/joeferner/redis-commander:latest
      restart: always
      environment:
      - REDIS_HOSTS=local:redis:6379
      ports:
      - "8081:8081"

volumes:
  redis_data:
    driver: local
